### ISSUE TITLE
How to get more details on error parsing files with Dredd

### ISSUE THREAD

**Issue by erajkovic** [apiaryio/dredd#1018]
#### Describe your problem

I am trying to automate the validation of the Swagger documents we have in our portal using Dredd to minimize the volume of data pushed to remote, and I am running into some issue with the setup. For some files, I get some processing done while it fails for some other files. The same Swagger files are loading fine to Apiary.

#### What command line options do you use?

Bad sample
```
$ dredd ./trc_api-test.json http://localhost:8080 --names --dry-run
warn: Parser warning in file './trc_api-test.json': 
Could not recognize API description format.
Falling back to API Blueprint by default.
 on line 1
warn: Parser warning in file './trc_api-test.json': ignoring possible metadata, expected '<key> : <value>', one one per line on line 1
info: Beginning Dredd testing...
complete: Tests took 1ms
```
Working sample
```
$ dredd ./failure1.json http://localhost:8080 --names --dry-run
error: Compilation error in file './failure1.json': Required URI parameter 'distpath' has no example or default value. ( > /services/{version}/sources/{distpath} > Delete an existing Oracle GoldenGate Distribution Path)
warn: Compilation warning in file './failure1.json': Ambiguous URI parameter in template: /services/{version}/sources/{distpath}
No example value for required parameter in API description document: distpath ( > /services/{version}/sources/{distpath} > Delete an existing Oracle GoldenGate Distribution Path)
...
```

#### What is in your `dredd.yml`?

```yaml
none - using only parameters
```

#### What's your `dredd --version` output?

```
dredd v5.1.6 (Darwin 17.4.0; x64)
```

#### Does `dredd --level=debug` uncover something?

Did not find any useful info, but will share in case I missed something.

```
dredd ./trc_api-test.json http://localhost:8080 --names --dry-run --level=debug
verbose: Loading configuration file: ./dredd.yml
debug: Dredd version: 5.1.6
debug: Node.js version: v8.9.1
debug: Node.js environment: http_parser=2.7.0, node=8.9.1, v8=6.1.534.47, uv=1.15.0, zlib=1.2.11, ares=1.10.1-DEV, modules=57, nghttp2=1.25.0, openssl=1.0.2m, icu=59.1, unicode=9.0, cldr=31.0.1, tz=2017b
debug: System version: Darwin 17.4.0 x64
debug: npm version: 5.5.1
debug: Configuration: {"server":"http://localhost:8080","options":{"_":["./trc_api-test.json"],"names":true,"n":true,"dry-run":true,"y":true,"level":"debug","l":"debug","hookfiles":null,"f":null,"language":"nodejs","a":"nodejs","sandbox":false,"b":false,"server":null,"g":null,"server-wait":3,"init":false,"i":false,"custom":{},"j":[],"only":[],"x":[],"reporter":[],"r":[],"output":[],"o":[],"header":[],"h":[],"sorted":false,"s":false,"user":null,"u":null,"inline-errors":false,"e":false,"details":false,"d":false,"method":[],"m":[],"color":true,"c":true,"timestamp":false,"t":false,"silent":false,"q":false,"path":["./trc_api-test.json","./trc_api-test.json"],"p":["./trc_api-test.json","./trc_api-test.json"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":1500,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":100,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"127.0.0.1","hooks-worker-handler-port":61321,"config":"./dredd.yml","$0":"dredd"},"custom":{"cwd":"/Users/erajkovi/Dev/git/dredd/failures","argv":["./trc_api-test.json","http://localhost:8080","--names","--dry-run","--level=debug"]}}
verbose: Using 'base' reporter.
verbose: Configuring reporters: []
verbose: Using 'cli' reporter.
verbose: 
HTTP(S) proxy specified by environment variables: NO_PROXY=localhost,127.0.0.1,erajkovi-mac,*.oracle.com,*.oraclecorp.com,/var/run/docker.sock, http_proxy=http://www-proxy.us.oracle.com:80, HTTPS_PROXY=http://www-proxy.us.oracle.com:80, https_proxy=http://www-proxy.us.oracle.com:80, no_proxy=localhost,127.0.0.1,erajkovi-mac,*.oracle.com,*.oraclecorp.com,/var/run/docker.sock, HTTP_PROXY=http://www-proxy.us.oracle.com:80. Please read documentation on how
Dredd works with proxies:
https://dredd.readthedocs.io/en/latest/how-it-works/#using-https-proxy

verbose: No backend server process specified, starting testing at once
verbose: Running Dredd instance.
verbose: Expanding glob patterns.
verbose: Reading API description files.
verbose: Parsing API description files and compiling a list of HTTP transactions to test.
verbose: Compiling HTTP transactions from API description file: ./trc_api-test.json
warn: Parser warning in file './trc_api-test.json': 
Could not recognize API description format.
Falling back to API Blueprint by default.
 on line 1
warn: Parser warning in file './trc_api-test.json': ignoring possible metadata, expected '<key> : <value>', one one per line on line 1
verbose: Starting reporters and waiting until all of them are ready.
```
#### Can you send us failing test in a Pull Request?

I know there is something wrong in the file, as it's also not parsed with fury, but I cannot get more detail there - here is the command used:

```
fury --validate ./trc_api-test.json 
Error: Document did not match any registered parsers!
    at Fury.parse (/usr/local/lib/node_modules/fury-cli/node_modules/fury/lib/fury.js:149:21)
    at Fury.validate (/usr/local/lib/node_modules/fury-cli/node_modules/fury/lib/fury.js:101:21)
...
```
Will try to find the smallest file from our set that can reproduce the problem and share it.

**Comment by kylef** [comment]
This is likely a bug in [fury-adapter-swagger](fury-adapter-swagger)'s Swagger detection logic (https://github.com/apiaryio/fury-adapter-swagger/blob/master/src/adapter.js#L14) where it is failing to detect your specific case.

@erajkovic could you please share the first few lines of the Swagger document (the ones that say something like `"swagger": "2.0"` and I'll get this fixed. No need for entire document.

**Comment by erajkovic** [comment]
{
  "swagger" : "2.0",
  "info" : {
    "description" : "Translational Research Center REST API",
    "version" : "3.2.0",
    "title" : "TRC 3.2 REST API"
  },
  "host" : "localhost:7001",
  "basePath" : "/HSDataService-web/api/3.2.0",
  "tags" : [ {
    "name" : "Administration",
    "description" : "Administration APIs"
  }, {
...

**Comment by honzajavorek** [comment]
The latest Dredd should not have this issue anymore. Please report back and let's reopen this if it's still a problem! Thanks!
