### ISSUE TITLE
Flaky test: "when using language hook handler and spawning the server and handler is killed before execution should return with status 1"

### ISSUE THREAD

**Issue by michalholasek** [apiaryio/dredd#1030]
Another annoying flaky little fellow in the Windows test suite:
```
1) CLI when called with arguments when using language hook handler and spawning the server and handler is killed before execution should return with status 1:
      AssertionError: expected 7 to equal 1
      + expected - actual
      -7
      +1
      
      at Context.it (C:\projects\dredd\test\integration\cli\cli-test.js:166:56)
      at callFn (C:\projects\dredd\node_modules\mocha\lib\runnable.js:334:21)
      at Test.Runnable.run (C:\projects\dredd\node_modules\mocha\lib\runnable.js:327:7)
      at Runner.runTest (C:\projects\dredd\node_modules\mocha\lib\runner.js:428:10)
      at C:\projects\dredd\node_modules\mocha\lib\runner.js:534:12
      at next (C:\projects\dredd\node_modules\mocha\lib\runner.js:348:14)
      at C:\projects\dredd\node_modules\mocha\lib\runner.js:358:7
      at next (C:\projects\dredd\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\projects\dredd\node_modules\mocha\lib\runner.js:326:5)
```

**Comment by honzajavorek** [comment]
It's back 😞
