### ISSUE TITLE
Buil failed on MacOs High Sierra (npm from brew)

### ISSUE THREAD

**Issue by radoslawkojdecki** [apiaryio/dredd#1095]
#### Describe your problem

Dredd failed to build on MacOs High Sierra. 
npm was installed using Homebrew (brew install npm).

#### What command line options do you use?

```
$ npm install -g dredd
```
#### Compiler output

```
  CXX(target) Release/obj.target/libsos/drafter/ext/sos/src/sos.o
  LIBTOOL-STATIC Release/sos.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
  CXX(target) Release/obj.target/protagonist/src/options_parser.o
../src/options_parser.cc:30:33: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
        const String::Utf8Value strKey(key);
                                ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/options_parser.cc:49:41: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
                const String::Utf8Value strValue(value);
                                        ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings generated.
  CXX(target) Release/obj.target/protagonist/src/parse_async.o
../src/parse_async.cc:61:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value sourceData(info[0]->ToString());
                      ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8.h:2851:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/parse_async.cc:128:14: error: no matching constructor for initialization of 'v8::TryCatch'
    TryCatch try_catch;
             ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8.h:8436:12: note: candidate constructor not viable: requires single argument 'isolate', but no arguments were provided
  explicit TryCatch(Isolate* isolate);
           ^
/Users/radoslaw.kojdecki/.node-gyp/10.7.0/include/node/v8.h:8556:3: note: candidate constructor not viable: requires 1 argument, but 0 were provided
  TryCatch(const TryCatch&) = delete;
  ^
1 warning and 1 error generated.
make: *** [Release/obj.target/protagonist/src/parse_async.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/dredd/node_modules/protagonist
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 (node_modules/dredd/node_modules/protagonist):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ dredd@5.1.11
updated 1 package in 114.096s
```

**Comment by honzajavorek** [comment]
@radoslawkojdecki The installation did not fail, only installation of an optional dependency did fail. See [Why I’m Seeing node-gyp or python Errors?](https://dredd.readthedocs.io/en/latest/installation.html#why-i-m-seeing-node-gyp-or-python-errors) Running `dredd --version` should work for you.

**Comment by radoslawkojdecki** [comment]
Thanks, confirmed - works :)
