### ISSUE TITLE
Flaky test on Windows: Babysitting Child Processes

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#1166]
**Describe the bug**

```
  1) Babysitting Child Processes
       when forcefully killed by childProcess.signalKill()
         process with support for graceful termination
           gets terminated:
      AssertionError: expected false to be true
      + expected - actual
      -false
      +true
      
      at Context.it (test\integration\child-process-test.js:72:42)
  
  2) Babysitting Child Processes
       when forcefully killed by childProcess.signalKill()
         process with support for graceful termination
           returns non-zero status code:
     AssertionError: expected undefined to be a number or a date
      at Context.it (test\integration\child-process-test.js:74:57)
  ```

**To Reproduce**
https://ci.appveyor.com/project/Apiary/dredd/builds/21114625

**Expected behavior**
The test passes or fails consistently.

**Comment by honzajavorek** [comment]
I haven't seen it lately, perhaps it was flaky CI environment? 🤔 Closing for now.
