### ISSUE TITLE
Not exiting server process on Travis CI

### ISSUE THREAD

**Issue by djragsdale** [apiaryio/dredd#1229]
**Describe the bug**
When running multiple Dredd tests as part of my Travis CI pipeline, all but the first test returns an "Address Already in Use" error. I was forced to manually kill the server process between Dredd tests.

**To Reproduce**
A Pull Request reproducing this behavior was created here: https://github.com/djragsdale/express-smoke-testing/pull/1 . I received the error when having my test command read `dredd --config dredd-api.yml && dredd --config dredd-pages.yml` as well as when making them subsequent lines in a bash script like can be seen in the `/scripts/good-smoke.sh` script. Both times, I received the following error.

```bash
info: Configuration 'dredd-api.yml' found, ignoring other arguments.
info: Starting backend server process with command: npm start
info: Waiting 3 seconds for backend server process to start
> express-smoke-testing@0.1.0 start /home/travis/build/djragsdale/express-smoke-testing
> node serve.js
Listening on port 3000...
info: Beginning Dredd testing...
info: Found Hookfiles:
pass: GET (200) /api/companies duration: 61ms
skip: GET (400) /api/companies
GET /api/companies 200 11.558 ms - 1877
pass: GET (200) /api/company/1 duration: 12ms
skip: GET (400) /api/company/1
complete: 2 passing, 0 failing, 0 errors, 2 skipped, 4 total
complete: Tests took 77ms
GET /api/company/1 200 0.996 ms - 38
info: Backend server process exited
info: Configuration 'dredd-pages.yml' found, ignoring other arguments.
info: Starting backend server process with command: npm start
info: Waiting 3 seconds for backend server process to start
> express-smoke-testing@0.1.0 start /home/travis/build/djragsdale/express-smoke-testing
> node serve.js
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/home/travis/build/djragsdale/express-smoke-testing/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/travis/build/djragsdale/express-smoke-testing/serve.js:7:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-smoke-testing@0.1.0 start: `node serve.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the express-smoke-testing@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-01-31T14_55_50_922Z-debug.log
```

**Expected behavior**
When running subsequent Dredd tests, the first test should end with `info: Backend server process exited`. At that point, the server process should be exited. When the second test runs the server script, it should not receive an "Address Already in Use" error. The second test should only fail if the actual Dredd test failed.

**What is in your `dredd.yml`?**

```yaml
dry-run: null
hookfiles: null
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd-api.yml
blueprint: api.yaml
endpoint: 'http://127.0.0.1:3000'
```

```yaml
dry-run: null
hookfiles: null
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd-pages.yml
blueprint: pages.apib
endpoint: 'http://127.0.0.1:3000'
```

**What's your `dredd --version` output?**

```
npm info dredd version
7.2.0
```

**Does `dredd --level=debug` uncover something?**
I have copied my output below. This was done with a `sleep 60s` between Dredd tests. All reporting from the first test had been completed long before the second test ran.

```bash
verbose: Wrapping up testing.
complete: 2 passing, 0 failing, 0 errors, 2 skipped, 4 total
complete: Tests took 85ms
verbose: Dredd instance run finished.
verbose: Exiting Dredd process with status '0'.
debug: Using native process.exit() method to terminate the Dredd process.
verbose: Terminating backend server process, PID 4409
verbose: Gracefully terminating the backend server process
GET /api/company/1 200 1.009 ms - 50
verbose: Gracefully terminating the backend server process
info: Backend server process exited
verbose: Loading configuration file: dredd-pages.yml
info: Configuration 'dredd-pages.yml' found, ignoring other arguments.
debug: Dredd version: 7.2.0
debug: Node.js version: v8.15.0
debug: Node.js environment: http_parser=2.8.0, node=8.15.0, v8=6.2.414.75, uv=1.23.2, zlib=1.2.11, ares=1.10.1-DEV, modules=57, nghttp2=1.33.0, napi=3, openssl=1.0.2q, icu=60.1, unicode=10.0, cldr=32.0, tz=2017c
debug: System version: Linux 4.4.0-101-generic x64
debug: npm version: 6.4.1
debug: Configuration: {"server":"http://127.0.0.1:3000","options":{"dry-run":null,"hookfiles":null,"language":"nodejs","require":null,"server":"npm start","server-wait":3,"init":false,"custom":{},"names":false,"only":[],"reporter":[],"output":[],"header":[],"sorted":false,"user":null,"inline-errors":false,"details":false,"method":[],"color":true,"level":"debug","timestamp":false,"silent":false,"path":["pages.apib","pages.apib"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":1500,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":100,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"127.0.0.1","hooks-worker-handler-port":61321,"config":"dredd-pages.yml","_":["pages.apib"],"p":["pages.apib","pages.apib"]},"custom":{"cwd":"/home/travis/build/djragsdale/express-smoke-testing","argv":["--config","dredd-pages.yml","--level=debug"]}}
verbose: Using 'base' reporter.
verbose: Configuring reporters: []
verbose: Using 'cli' reporter.
verbose: Backend server process specified, starting backend server and then testing
verbose: Using 'npm' as a server command, ["start"] as arguments
info: Starting backend server process with command: npm start
info: Waiting 3 seconds for backend server process to start
> express-smoke-testing@0.1.0 start /home/travis/build/djragsdale/express-smoke-testing
> node serve.js
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::3000
```

**Can you send us failing test in a Pull Request?**
My repository's failing test can be seen here: https://github.com/djragsdale/express-smoke-testing/pull/1 . I will attempt to create a test within Dredd that reproduces the error and place it in a Pull Request.

**Comment by honzajavorek** [comment]
@djragsdale Thanks for filing this! I just noticed a similar issue here: https://github.com/apiaryio/dredd-example/issues/36

I didn't have time to dig into it in a thorough way, but my hunch would be it might be all because of https://github.com/apiaryio/dredd/issues/793 Both your case and the dredd-example case uses `npm start`, which might behave in a similar way as running from a bash script.

I'm not able to reproduce this on Windows and not even on macOS most of the time, so it might besomething Linux-specific as well.

This is definitely a bug we should be looking into. The right place where to look is the [enhanced child process](https://github.com/apiaryio/dredd/blob/master/lib/childProcess.js) and [its tests](https://github.com/apiaryio/dredd/blob/master/test/integration/childProcess-test.js).

**Comment by djragsdale** [comment]
@honzajavorek I understand the "symptom vs. root cause" of the situation, but I think we can handle the symptom in this case and be fine. We can't go through and find the nested processes we've created, but we can close the process listening on the TCP port we need. We could also check for the port being closed after we kill all processes. I'll try adding tests both for when we are forgetting to re-open the port and for when the port is already in use.
