### ISSUE TITLE
error: Error connecting to server under test!

### ISSUE THREAD

**Issue by avinashkdeshmukh** [apiaryio/dredd#1285]
Hi,
I am facing below issue. This is for both 
1. connecting to apiary server
2. to connect server under test.

all proxies are set up properly.
![proxy-snapshot](https://user-images.githubusercontent.com/45139815/54803484-b27ec000-4c95-11e9-8f4b-46c0ef12d823.png)

Kindly help to resolve the issue

Details:
dredd version: 
dredd v8.0.6 (Windows_NT 6.3.9600; x64)

npm version: 
6.4.1

Below files are attached
[ex.zip](https://github.com/apiaryio/dredd/files/2995137/ex.zip)

Exception details:
2019-03-22T05:21:38.921Z - debug: Running 'before' hooks
2019-03-22T05:21:38.924Z - debug: Emitting to reporters: test start
2019-03-22T05:21:38.929Z - debug: Performing HTTPS request to the server under t
est: GET https://polls.apiblueprint.org/questions
2019-03-22T05:21:39.976Z - debug: Handling HTTPS response from the server under
test
**2019-03-22T05:21:39.980Z - debug: Requesting tested server errored: Error: conne
ct ECONNREFUSED 52.4.75.11:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
2019-03-22T05:21:39.982Z - debug: Emitting to reporters: test error
error: Error connecting to server under test!
error: GET (200) /questions duration: 1057ms**
2019-03-22T05:21:39.988Z - debug: Running 'afterEach' hooks
2019-03-22T05:21:39.989Z - debug: Running 'after' hooks
2019-03-22T05:21:39.991Z - debug: Evaluating results of transaction execution #1
: /questions > GetQuesions > 200 > application/json
**2019-03-22T05:21:39.993Z - debug: No emission of test data to reporters { Error:
 connect ECONNREFUSED 52.4.75.11:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '52.4.75.11',
  port: 443 }**
2019-03-22T05:21:39.997Z - debug: Running 'afterAll' hooks
2019-03-22T05:21:39.999Z - debug: Wrapping up testing.
info: Displaying failed tests...
fail: GET (200) /questions duration: 1057ms
fail: Error connecting to server under test!
2019-03-22T05:21:40.005Z - debug: Could not stringify:
request:
method: GET
uri: /questions
headers:
    Content-Type: application/json
    Accept: application/json
    User-Agent: PostmanRuntime/7.6.1
    connection: keep-alive

body:

expected:
headers:
    Content-Type: application/json

body:
[
  {
    "urL": "aute laborum consequat",
    "question": "ea nulla qui pariatur dolor",
    "published_at": "Duis",
    "choices": []
  }
]
statusCode: 200
bodySchema: {"type":"array","items":{"type":"object","properties":{"urL":{"type"
:"string"},"question":{"type":"string"},"published_at":{"type":"string"},"choice
s":{"type":"array","items":{"type":"object","properties":{"url":{"type":"string"
},"choice":{"type":"string"},"votes":{"type":"number"}},"required":["choice"]}}}
}}

complete: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total
complete: Tests took 2370ms
2019-03-22T05:21:40.024Z - debug: Dredd instance run finished.
2019-03-22T05:21:40.026Z - debug: Using native process.exit() method to terminat
e the Dredd process with status '1'.
2019-03-22T05:21:40.027Z - debug: The backend server process has already termina
ted

**Comment by honzajavorek** [comment]
It seems you're using HTTP(S) proxy. [This section in documentation](https://dredd.org/en/latest/how-it-works.html#using-https-proxy) could help you to set up Dredd properly.

**Comment by honzajavorek** [comment]
@avinashkdeshmukh Closing this now, I hope you were able to find a solution. If you happen to have time to share it here, it might help others as well when they find this issue. If your problems persist, let us know here or in a new issue. Cheers 🙂
