### ISSUE TITLE
Authenticate requests with Oauth

### ISSUE THREAD

**Issue by avinashkdeshmukh** [apiaryio/dredd#1290]
**Describe the bug**
I am trying to test a service contract in OpenAPI 3. All the information for security schema and security requirement objects are defined properly.
The flow should be
1. Token Url should be called before all request to get the token
2. All other calls should happen with token from step #1 in the header of other requests.

But token is not embedding in the other requests.

Note: Here we cant use before all hook to get the token and keep in the stash and letter use it in 
request header as token url is not same as server url. Because of the which token end point cant be part of yml file.

**To Reproduce**
using dredd configuration file.

**Expected behavior**
Requests should be authenticated.

**What is in your `dredd.yml`?**
color: true
dry-run: null
hookfiles: dreddhook.js
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
custom: 
names: false
only: []
reporter: [cli]
output: [C:\logs]
header: []
sorted: false
user: ****:*****
inline-errors: true
details: true
method: []
loglevel: debug
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: test.yaml
endpoint: 'https://************'

**What's your `dredd --version` output?**

```
dredd v8.0.6 (Windows_NT 10.0.16299; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
No

**Comment by honzajavorek** [comment]
Hi, auth is not supported by Dredd out of the box at this moment. The workaround would be to figure out a solution using hooks. You write

> we cant use before all hook to get the token and keep in the stash and letter use it in
request header as token url is not same as server url. Because of the which token end point cant be part of yml file.

but could you make a custom request to get the token, e.g. using a [request](https://github.com/request/request) library inside a `beforeAll()` hook?

**Comment by avinashkdeshmukh** [comment]
Thanks honzajavorek for your quick response.
I will try that and let you know.

**Comment by avinashkdeshmukh** [comment]
Hi 
I have tried that but it is throwing below error. Its not ale to find request module.
Tried installing request explicitly despite the fact that it is already there with npm.

2019-03-26T12:35:15.540Z - warn: Skipping hook loading. Error reading hook file 'C:\dreddhook.js'. This probably means one or more of your hook files are invalid.
Message: Cannot find module 'request'
Stack:
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Proxyquire._require (C:\Users\<username>\AppData\Roaming\npm\node_modules\dredd\node_modules\proxyquire\lib\proxyquire.js:193:19)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\dreddhook.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) (C:\Users\<username>\AppData\Roaming\npm\node_modules\dredd\node_modules\proxyquire\lib\proxyquire.js:305:43)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

Below is the hook file content for beforeAll

const hooks = require("hooks");
const request = require('request');
stash = {}

hooks.beforeAll(function(transaction){
	
	const url = 'https://idsrv-uat.orientsys.com.au/core/4/connect/token';
	const formData = {
		grant_type: 'password',
		username: '***********',
		password: '************',
		scope: 'scpop1 scope2'
	};
	request.post({url: url, formData: formData},function(error, response, body){
		hooks.log('after get token .....');
		hooks.log(response);
		hooks.log(body);
	});
})
Kindly help.

**Comment by kettanaito** [comment]
Hello, @avinashkdeshmukh. I believe the issue is about the way modules of the hook files (in your case `C:\dreddhook.js`) are loaded. Dredd is using `proxyquire`, which fails to find the `request` module during the execution of your hook:

https://github.com/apiaryio/dredd/blob/d9841357eacb70f20eb3a6538b357bb343a14869/lib/addHooks.js#L25

May I please suggest you to install the `request` package globally, to see if it alters the current behavior?

```bash
npm i request -g
```

If that doesn't help, or the package is already installed globally, we would need to double check the modules handling on the `proxyquire` configuration we provide. What do you think, @honzajavorek?

**Comment by honzajavorek** [comment]
I agree, this should be possible with the Node.js hooks. If it's not, it's a serious flaw.

**Comment by avinashkdeshmukh** [comment]
Thanks for your inputs.
That error is resolved by installing package.

But actual problem of getting token will not work with request package.
Reason is request uses  http module. This, by nature is a async call.

try {
    self.req = self.httpModule.request(reqOptions)
  } catch (err) {
    self.emit('error', err)
    return
  }

In this scenario, it looks like dredd is running hook on separate thread where token request is happening. But this thread does not have a mechanism to send the requested data to caller.

Solution is to run it in a synchronous way.
There are various ways we can do that. With that approach it is working now.

Another issues is by default dredd tests only 200 status. 
Overriding skip parameter I was able to make it to test all status codes.
However, while testing 403 (forbidden) status for an endpoint, service is returning 200 status as dredd is forming a valid request. This test will always fail.

How to verify those status code?  In this case tool needs to form request for which API under test would return 403.
Overriding the request parameter in the before hook for every request may not be feasible as if API document has more number of endpoints, it would be very difficult and code would be error prone.

**Comment by honzajavorek** [comment]
@avinashkdeshmukh I'm sorry for missing your last response. Thanks for sharing your progress here, I think it will definitely help others as well. Were you able to resolve the last step somehow?
