### ISSUE TITLE
"EADDRINUSE" error during smoke tests

### ISSUE THREAD

**Issue by artem-zakharchenko** [apiaryio/dredd#1511]
**Describe the bug**
During the current Dredd's smoke tests there is an `EADDRINUSE` exception being thrown when trying to run `dredd-example`:

```
Listening on port 3000
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1298:14)
    at listenInCluster (net.js:1346:12)
    at Server.listen (net.js:1434:7)
    at Function.listen (/home/circleci/project/dredd-example/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/circleci/project/dredd-example/app.js:216:5)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1325:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
```

* [Job example in CircleCI](https://circleci.com/gh/apiaryio/dredd/270)

**To Reproduce**
Perform a fresh CI build.

**Expected behavior**
I would expect smoke tests to not throw any exceptions and confirm Dredd usable.

---

Since this is happening for a while, I wonder if that's an expected behavior. I would appreciate @honzajavorek involvement in this discussion.

**Comment by honzajavorek** [comment]
This is a known issue of an unknown origin. Documented in https://github.com/apiaryio/dredd-example/issues/36 and kind of in https://github.com/apiaryio/dredd/issues/1229 as well.

**Comment by honzajavorek** [comment]
I'll close this as duplicate, but it's definitely a valid bug report.
