### ISSUE TITLE
Dredd on Docker with ruby hooks fail to run

### ISSUE THREAD

**Issue by slim1979** [apiaryio/dredd#1777]
**Describe the bug**
I use dredd in docker container. Rails server is also in docker.
When I run dredd with ruby hooks, I get `HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`

**To Reproduce**
To reproduce set language to ruby, use hooks.rb with some hooks

**Expected behavior**
Expected to test is running without any errors

**What is in your `dredd.yml`?**
```yaml
color: true      
hookfiles: ./hooks.rb
language: ./dummy_script    
require: null    
server: null    
server-wait: null    
init: true    
custom: {}    
only: []    
reporter: ['html']
output: []
header: ['Authorization: Bearer some-hash', 'Content-Type: application/json']
sorted: false
user: null
inline-errors: true
details: true
method: []
loglevel: debug
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 1000
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: Rails server host
hooks-worker-handler-port: 3000
config: ./dredd.yml
blueprint: ./albums.json
endpoint: Rails_server_host:3000
```

**What's your `dredd --version` output?**

```
dredd v13.1.1 (Linux 4.4.0-53-generic; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
```yaml
2020-06-22T12:00:41.204Z - debug: Dredd version: 13.1.1
2020-06-22T12:00:41.205Z - debug: Node.js version: v14.4.0
2020-06-22T12:00:41.205Z - debug: Node.js environment: node=14.4.0, v8=8.1.307.31-node.33, uv=1.37.0, zlib=1.2.11, brotli=1.0.7, ares=1.16.0, modules=83, nghttp2=1.41.0, napi=6, llhttp=2.0.4, openssl=1.1.1g, cldr=37.0, icu=67.1, tz=2019c, unicode=13.0
2020-06-22T12:00:41.206Z - debug: System version: Linux 4.4.0-53-generic x64
2020-06-22T12:00:41.211Z - debug: npm version: [object Object]
2020-06-22T12:00:41.211Z - debug: Configuration: {"color":true,"hookfiles":"./hooks.rb","require":null,"server":"http://lms-api.loc:3000","server-wait":null,"init":true,"custom":{"cwd":"/","argv":["--language","./dummy_script","--dry-run","-f","./hooks.rb"]},"only":[],"reporter":["html"],"output":[],"header":["Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMzUxMzg2ODB9.EoDeKyR7KSMFZKlKF0dIZ-GPqwPk2o4acc2CvCre5-w","Content-Type: application/json"],"sorted":false,"user":null,"inline-errors":true,"details":true,"method":[],"loglevel":"debug","path":["./albums.json","./albums.json"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":1500,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":1000,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"lms-api.loc","hooks-worker-handler-port":3000,"config":"./dredd.yml","_":["./albums.json"],"language":"./dummy_script","dry-run":true,"f":"./hooks.rb","p":["./albums.json","./albums.json"]}
2020-06-22T12:00:41.213Z - debug: No backend server process specified, starting testing at once
2020-06-22T12:00:41.213Z - debug: Running Dredd instance.
2020-06-22T12:00:41.213Z - debug: Resolving --require
2020-06-22T12:00:41.213Z - debug: Configuring reporters
2020-06-22T12:00:41.213Z - debug: Using 'base' reporter.
2020-06-22T12:00:41.215Z - debug: Configuring reporters: [ 'html' ]
2020-06-22T12:00:41.215Z - debug: Using 'cli' reporter.
2020-06-22T12:00:41.215Z - warn: 
There are more reporters requiring output paths than there are output paths
provided. Using default paths for additional file-based reporters.

2020-06-22T12:00:41.216Z - warn: File exists at /report.html, will be overwritten...
2020-06-22T12:00:41.216Z - debug: Using 'html' reporter.
2020-06-22T12:00:41.216Z - debug: Preparing API description documents
2020-06-22T12:00:41.216Z - debug: Resolving locations of API description documents
2020-06-22T12:00:41.218Z - debug: Reading API description documents
(node:25726) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
2020-06-22T12:00:41.235Z - debug: Parsing API description documents
2020-06-22T12:00:41.308Z - debug: Compiling HTTP transactions from API description documents
2020-06-22T12:00:41.315Z - debug: Starting the transaction runner
2020-06-22T12:00:41.315Z - debug: Starting reporters and waiting until all of them are ready
2020-06-22T12:00:41.315Z - debug: Beginning Dredd testing...
2020-06-22T12:00:41.315Z - debug: Sorting HTTP transactions
2020-06-22T12:00:41.315Z - debug: Configuring HTTP transactions
2020-06-22T12:00:41.318Z - debug: Reading hook files and registering hooks
2020-06-22T12:00:41.319Z - debug: Found Hookfiles: 0=/hooks.rb
2020-06-22T12:00:41.324Z - debug: Looking up hooks handler implementation: ./dummy_script
2020-06-22T12:00:41.324Z - debug: Using './dummy_script' as a hooks handler command, '' as arguments
2020-06-22T12:00:41.325Z - debug: Starting hooks handler.
2020-06-22T12:00:41.325Z - debug: Spawning './dummy_script' hooks handler process.
2020-06-22T12:00:41.330Z - debug: Connecting to hooks handler.
2020-06-22T12:00:41.832Z - debug: Starting TCP connection with hooks handler process.
2020-06-22T12:00:41.841Z - debug: Successfully connected to hooks handler. Waiting 1s to start testing.
2020-06-22T12:00:42.842Z - debug: Registering hooks.
2020-06-22T12:00:42.843Z - debug: Executing HTTP transactions
2020-06-22T12:00:42.843Z - debug: Running 'beforeAll' hooks
2020-06-22T12:00:42.844Z - debug: Running hooks...
2020-06-22T12:00:42.846Z - debug: Sending HTTP transaction data to hooks handler: afc7273c-74d1-4e5b-873d-7a7395fd1289
(node:25726) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.
2020-06-22T12:00:42.848Z - debug: Dredd received some data from hooks handler.
undefined:1
HTTP/1.1 400 Bad Request
^

SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/usr/lib/node_modules/dredd/build/HooksWorkerClient.js:286:44)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```
dummy_script
```bash
function term() {
    echo 'Caught SIGTERM, exiting.'
    exit 0
}

trap 'term' SIGTERM

while true
do
   sleep 1
done
```
hooks.rb
```ruby
require 'dredd_hooks/methods'

include DreddHooks::Methods


puts 'ok'

before_all do |trans|
  puts trans
  # request.headers['Authorization'] = 'Bearer hash'
end
```
on sever side I see `HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`

if I run dredd without language set, test is runnig, but I get this 
```html
Dredd Tests
Error: GET (200) /api/albums

Error: 
Error: unknown format "int32" is used in schema at path "#/properties/id"
Stacktrace: 
Error: unknown format "int32" is used in schema at path "#/properties/id"
    at Object.format [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:68957)
    at Object.mt [as validate] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:33699)
    at Object.properties [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:85734)
    at mt (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:33699)
    at $a.P (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:35894)
    at $a.Xr (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:22292)
    at Object.b [as resolveRef] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:36799)
    at Object.$ref [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:55210)
    at Object.mt [as validate] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:32264)
    at Object.items [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:75190)
Summary
Tests completed: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total.

Tests took: 1735ms.
```
**Can you send us failing test in a Pull Request?**
possibly yes

**Comment by slim1979** [comment]
possibly, resolved, with language set dredd-hooks-ruby ./hooks.rb, but didn't resolved format issue:
```html
Dredd Tests
Error: GET (200) /api/albums

Error: 
Error: unknown format "int32" is used in schema at path "#/properties/id"
Stacktrace: 
Error: unknown format "int32" is used in schema at path "#/properties/id"
    at Object.format [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:68957)
    at Object.mt [as validate] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:33699)
    at Object.properties [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:85734)
    at mt (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:33699)
    at $a.P (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:35894)
    at $a.Xr (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:22292)
    at Object.b [as resolveRef] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:36799)
    at Object.$ref [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:55210)
    at Object.mt [as validate] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:32264)
    at Object.items [as code] (/usr/lib/node_modules/dredd/node_modules/gavel/build/index.js:3:75190)
Summary
Tests completed: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total.

Tests took: 134ms.
```

**Comment by slim1979** [comment]
@honzajavorek would you please help?

**Comment by honzajavorek** [comment]
I’m no longer involved in the project, but it looks like Dredd receives the following, literally, as the response from the hooks:

```
undefined:1
HTTP/1.1 400 Bad Request
```

The protocol between Dredd and the hooks is based on JSON though, so Dredd expects JSON, tries to parse it, and that obviously blows up. The solution is in figuring out why the hooks send such payload.

The “int32” issue isn’t related I think and I’d say it’s a known problem - OpenAPI in some cases don’t comply 1:1 with JSON Schema and the Apiary tooling is yet to support some of the custom types. I’m lazy atm to find the corresponding issue here on GitHub, but I believe there has been one.

**Comment by slim1979** [comment]
@honzajavorek sorry for inviting you to this conversations) can you tell me, how can I see, what data dredd is sending to the host? why server respond with `HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>` ?

**Comment by slim1979** [comment]
resolved with `language: bundle exec dredd-hooks-ruby` and remove hooks-worker-host and port

**Comment by honzajavorek** [comment]
No problem :) I mentioned it not to make you feel guilty, but for context.
I’ve read your message and I felt I can help, so I replied. I’m glad you
got it working!
