### ISSUE TITLE
Pitboss error

### ISSUE THREAD

**Issue by philsturgeon** [apiaryio/dredd#180]
Dredd was running fine locally on my node v0.10.something, but CirlceCI is falling over:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'pitboss'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/nvm/v0.10.33/lib/node_modules/dredd/lib/transaction-runner.js:22:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

at Module.require (module.js:364:17)
```

Dunno what the heck this means, as I'm about as good at NodeJS as I am at speaking Mongolian. 

I tried a few logical things, like installing the latest version of NodeJS, but trying to `npm -g install dredd` on OS X gave me other errors:

```
/Users/phil/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/boxen/nodenv/versions/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/opt/boxen/nodenv/versions/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/boxen/nodenv/versions/v0.12.2/lib/node_modules/dredd/node_modules/protagonist
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "/opt/boxen/nodenv/versions/v0.12.2/bin/node" "/opt/boxen/nodenv/versions/v0.12.2/bin/npm" "-g" "install" "dredd"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.17.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.17.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/phil/src/central_api/npm-debug.log
```

The output of that log can be found here:

https://gist.githubusercontent.com/philsturgeon/89b614a3a05a44a4f519/raw/gistfile1.txt

Can somebody make my problems go away?

**Comment by netmilk** [comment]
@philsturgeon Thanks for the report. I'll release new version of Dredd with support for node 0.12 in a while and I hope your problems will go away.  :)

**Comment by netmilk** [comment]
@philsturgeon Released, please try it and let me know if it does work for you.

**Comment by philsturgeon** [comment]
Thanks! That fixed it :D 

-- 
Phil
