### ISSUE TITLE
Multipart request parser error

### ISSUE THREAD

**Issue by pgconreaux** [apiaryio/dredd#244]
When attempting a multipart JAR file upload, I get the parse error shown below.
Here is the request (omitted binary data for brevity):

```
+ Request (multipart/form-data;boundary=BOUNDARY)
    + Headers

            Authorization: qwertyqwerty


    + Body

            --BOUNDARY
            Content-Disposition: form-data; name="filename"; filename="example.jar"
            Content-Type: application/java-archive

            [binary data pasted here]
            --BOUNDARY--
```

Here is the parse error (also prints a warning stating that response is missing):

```
warn: Parser warning in file 'blueprints/workflows/install.md': (6) action is missing a response for a request on line 27
/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/lib/blueprint-ast-to-runtime.js:105
            transaction['request']['uri'] = uriResult['uri'];
                                          ^
TypeError: Cannot set property 'uri' of undefined
  at blueprintAstToRuntime (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/lib/blueprint-ast-to-runtime.js:105:43)
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/lib/dredd.js:229:21
  at done (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/async/lib/async.js:132:19)
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/async/lib/async.js:32:16
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/lib/dredd.js:198:18
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/drafter/lib/drafter.js:194:18
  at done (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/async/lib/async.js:132:19)
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/async/lib/async.js:32:16
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/drafter/lib/drafter.js:234:16
  at generateSchema (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/drafter/lib/drafter.js:114:12)
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/drafter/lib/drafter.js:233:14
  at generateBody (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/drafter/lib/drafter.js:87:12)
  at Drafter.resolvePayload (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/drafter/lib/drafter.js:229:12)
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/async/lib/async.js:122:13
  at _each (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/async/lib/async.js:46:13)
  at Object.async.each (/Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/async/lib/async.js:121:9)
  at /Users/patrickconreaux/.nvm/versions/node/v0.12.0/lib/node_modules/dredd/node_modules/drafter/lib/drafter.js:192:22
```

I have also tried writing the data to the request body in a hook, but the calculated content length isn't as expected (much larger than multipart request + file size). I can provide more details if necessary.
A working example of a multipart binary file upload would be very helpful.

Cheers,
Patrick

**Comment by netmilk** [comment]
Hi @pgconreaux,

I'm sorry for response this late and thank you very much for the report. Dredd definitely should not crash like this in any case. Would you mind sending me whole blueprint or at least parent section for this request? It will be very helpful.

Thanks!
A

**Comment by honzajavorek** [comment]
Since @pgconreaux didn't get back and at the same time I think we've resolved an issue with the same error message, I'll consider this as closed. Feel free to come back and comment if this is still broken in the latest Dredd version.
