### ISSUE TITLE
Missing trailing slash after host causes exception

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#260]
As mentioned in edit #126 if you omit leading protocol and trailing slash it results in a crash:

```
$ dredd apiary.apib localhost:3000
```

instead of:

```
$ dredd apiary.apib http://localhost:3000
```

or

```
$ dredd apiary.apib localhost:3000/
```

it results in crash:

```
/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/transaction-runner.js:278
      fullPath = '/' + [this.parsedUrl['path'].replace(/^\/|\/$/g, ""), reques
                                              ^
TypeError: Cannot read property 'replace' of null
  at TransactionRunner.configureTransaction (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/transaction-runner.js:278:47)
  at TransactionRunner.configureTransaction (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/transaction-runner.js:3:57)
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/async/lib/async.js:246:17
  at iterate (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/async/lib/async.js:146:13)
  at async.eachSeries (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/async/lib/async.js:162:9)
  at _asyncMap (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/async/lib/async.js:245:13)
  at Object.mapSeries (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/async/lib/async.js:228:23)
  at TransactionRunner.run (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/transaction-runner.js:56:11)
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:249:33
  at EventEmitter.<anonymous> (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/reporters/cli-reporter.js:24:14)
  at EventEmitter.emit (events.js:129:20)
```

**Comment by honzajavorek** [comment]
I believe @pksunkara was hit by this as well.
