### ISSUE TITLE
Cannot install Dredd on Windows 10, Node 5.3.0

### ISSUE THREAD

**Issue by 3dtomato** [apiaryio/dredd#318]
I cannot install Dredd on Windows 10 

My configuration is:
- Windows 10 x64 10586.36
- Visual Studio 2015 Comunity
- Python 2.7.11
- Node 5.3.0
- NPM 3.3.12

```
PS C:\WINDOWS\system32> npm install -g dredd
npm WARN engine uri-template@1.0.0: wanted: {"node":"~0.10.4"} (current: {"node":"5.3.0","npm":"3.3.12"})
C:\Users\tomas\AppData\Roaming\npm\dredd -> C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\bin\dredd

> protagonist@1.2.2 install C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist
> node-gyp rebuild


C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\tomas\AppDat
a\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\libdrafter.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\libdrafter.vcxproj]


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\tomas\AppDat
a\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\ext\snowcrash\libmarkdownparser.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\ext\snowcrash\libmarkdownparser.vcxproj]


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\tomas\AppDat
a\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\ext\snowcrash\libsnowcrash.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\ext\snowcrash\libsnowcrash.vcxproj]


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\tomas\AppDat
a\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\libsos.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\libsos.vcxproj]


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\tomas\AppDat
a\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\ext\snowcrash\libsundown.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist\build\drafter\ext\snowcrash\libsundown.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:protagonist@1.2.2 protagonist@1.2.2 install: `node-gyp rebuild`
npm WARN install:protagonist@1.2.2 Exit status 1

> spawn-sync@1.0.14 postinstall C:\Users\tomas\AppData\Roaming\npm\node_modules\dredd\node_modules\spawn-sync
> node postinstall

C:\Users\tomas\AppData\Roaming\npm
└── (empty)

npm ERR! code 1
```

```
PS C:\WINDOWS\system32> npm config list
; cli configs
user-agent = "npm/3.3.12 node/v5.3.0 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\tomas\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\WINDOWS\system32
; HOME = C:\Users\tomas
; "npm config ls -l" to show all defaults.
```
Btw, is it really needed to install whole MS Visual Studio 2015? It's approx 6-8GB! :( Wouldn't be enough some SDK?

**Comment by 3dtomato** [comment]
Ok, finally the installation is working. I have had to make custom installation of MS Visual 2015 and check `Common Tools for Visual C++ 2015`. Anyway, VS2015 takes approx. 9GB. Isn't there any other option with smaller SDK?

**Comment by netmilk** [comment]
> Ok, finally the installation is working.

Glad to hear that! 😃

> Anyway, VS2015 takes approx. 9GB.

Sad to hear that! 😔

Perhaps @kylef, @pksunkara, @w-vi or @klokane may help?

**Comment by pksunkara** [comment]
You can use VS2013.
