### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by lippea** [apiaryio/dredd#424]
I tried to run with below response MSON, but it throws an error.
The error is gone if the last line of "- name:abc" is removed
+ Response 200 (application/json; charset=UTF-8)

    + Attributes
        - _source (object, required)
            - events (array, fixed)
                - (object)
                    - name: Sent
                    - timeUtc: Wed, 16 Mar 2016 22:29:50 GMT (string)
                    - metadata
                        - response
                            - Formfields
                                - item (array)
                                    - (object)
                                        - name: abc

Error:
warn: Parser warning in file 'BluePrints/analytics-enquiry-course.apib': (4) no property name
C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\node_modules\blueprint-transactions\lib\blueprint-ast-to-runtime.js:25
  if (blueprintAst['name'] !== "") {
                  ^

TypeError: Cannot read property 'name' of undefined
  at blueprintAstToRuntime (C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\node_modules\blueprint-transactions\lib\blueprint-ast-to-runtime.js:25:19)
  at Object.module.exports.compile (C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\node_modules\blueprint-transactions\lib\blueprint-transactions.js:11:14)
  at Dredd.compileTransactions (C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\lib\dredd.js:285:44)
  at C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\lib\dredd.js:117:26
  at C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\lib\dredd.js:272:16
  at done (C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\node_modules\async\lib\async.js:132:19)
  at C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\node_modules\async\lib\async.js:32:16
  at C:\Users\lhuang\AppData\Roaming\npm\node_modules\dredd\lib\dredd.js:245:18

**Comment by honzajavorek** [comment]
Hi @lippea, this happens when parser doesn't return anything Dredd could consume. It's Dredd bug documented at #403. However, Dredd crash is just a consequence of a prior error from parser, not a reason why the testing doesn't work.

The true reason can be probably tracked down by inspecting the warning you are getting:

> warn: Parser warning in file 'BluePrints/analytics-enquiry-course.apib': (4) no property name

You write that

>  The error is gone if the last line of "- name:abc" is removed

but I can't see any `- name:abc` part in the sample you provided. It seems like the sample is indeed missing a property name on the last line, as the parser warns. Could you please check your input and verify, whether your blueprint is valid? If your blueprint is valid and parser or Dredd crash, then we'll definitely treat this as a bug, but currently it seems to me that parser just fails to parse your blueprint and Dredd fails to gracefully terminate (#403).

**Comment by lippea** [comment]
Hi @honzajavorek, I believe the input is valid. The "- name: abc" is at the bottom of the input.
I agree with you that it's a prior error from parser. But I'm not sure how can I check further on generated schema or something else to identify which part exactly causes the error.

**Comment by honzajavorek** [comment]
@lippea Now I can see it, thanks! It seems like GitHub originally didn't format properly the issue description for me, not sure why. I'll try to investigate what might be the problem.

**Comment by honzajavorek** [comment]
I was able to reproduce the issue. I created following API Blueprint document:

```apib
FORMAT: 1A

# Hotels API

# Group Hotels

## Hotels [/hotels]

### Get Hotel [GET]

+ Response 200 (application/json)

    + Attributes
        - _source (object, required)
            - events (array, fixed)
                - (object)
                    - name: Sent
                    - timeUtc: Wed, 16 Mar 2016 22:29:50 GMT (string)
                    - metadata
                        - response
                            - Formfields
                                - item (array)
                                    - (object)
                                        - name: abc
```

Then I tried to validate it with [Drafter](https://github.com/apiaryio/drafter):

```
$ brew install --HEAD https://raw.github.com/apiaryio/drafter/master/tools/homebrew/drafter.rb
$ drafter ./blueprint.apib
element: "parseResult"
content:
  -
    element: "annotation"
    meta:
      classes:
        - "warning"
    attributes:
      code: 4
      sourceMap:
        -
          element: "sourceMap"
          content: []
    content: "no property name"

OK.
warning: (4)  no property name
```

So indeed, given MSON produces a warning and an incomplete output (which causes Dredd to fail - #403). Now let's investigate whether this is expected behavior or a Drafter issue. I tried to reduce the blueprint to a minimal failing example and came to this:

```apib
FORMAT: 1A

# Hotels API

# Group Hotels

## Hotels [/hotels]

### Get Hotel [GET]

+ Response 200 (application/json)

    + Attributes
        - property
            - property
                - property
                    - property
                        - property
                            - property
                                - property
                                    - property
                                        - property: value
```

If I remove a single property (one indentation level) from this, Drafter successfully parses the document. That makes me think this is Drafter limitation to process 9 and more levels of nesting. Not sure whether it's a known limitation or a bug, but since @lippea's example came from a real world situation, it seems to me we should be able to parse this. I filed

**Comment by lippea** [comment]
@honzajavorek Thanks very much for investigating this.
In the drafter issue, this interests me: "break down their blueprint into separate data structures."
Looks like a way to get around this issue. Is it customized data structure?

**Comment by lippea** [comment]
Is there an example of how to break it down?
I tried the following, but doesn't look work: it's always pass.
+ Response 200 (application/json; charset=UTF-8)

    + Attributes
        # customizedobject (object)
            - name: Sent
            - timeUtc: Wed, 16 Mar 2016 22:29:50 GMT (string)
                - metadata
                    - response
                        - Formfields
                            - item (array)
                                - (object)
                                    - name: abc
        - _source (object, required)
            - events (array, fixed)
                - (customizedobject)

**Comment by lippea** [comment]
Tried below as well. It's still always pass.
```
+ Response 200 (application/json; charset=UTF-8)

    + Attributes
        # customizedobject (object)
            - name: abc
        - _sourced (object, required)
            - eventss (array, fixed)
                - (object)
                    - name: Sent
                    - timeUtc: Wed, 16 Mar 2016 22:29:50 GMT (string)
                    - metadata
                        - response
                            - Formfields
                                - item (array)
                                    - (customizedobject)
```
Looks like the schema generated is empty:
```
expected:
headers:
    Content-Type: application/json; charset=UTF-8

body:
{}
statusCode: 200
bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {}
}
```

**Comment by honzajavorek** [comment]
@lippea I'm sorry for my late response. To break down large structures, you can use advanced MSON techniques, such as inheritance or includes. In [repository of API Blueprint examples](https://github.com/apiaryio/api-blueprint/tree/master/examples) you can find [Data Structures example](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/10.%20Data%20Structures.md), which shows inheritance:

```apib
...

### Create a Coupon [POST]
Creates a new Coupon.

+ Attributes (Coupon Base)

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Coupon)

# Data Structures

## Coupon Base (object)
+ percent_off: 25 (number)

    A positive integer between 1 and 100 that represents the discount the coupon will apply.

+ redeem_by (number) - Date after which the coupon can no longer be redeemed

...
```

You can also use includes (a.k.a. mixins). I haven't found any official examples of full blueprints with includes, but the [code fragments shown in the MSON Specification for the Include statement](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#51-mixin-type) should give you the clue. My take would be:

```apib
### Retrieve a User [GET]
Retrieve a User.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (User)

# Data Structures

## User (object)
+ socks_size: 42 (number)
+ Include CustomerMixin

## Company (object)
+ name: Apple (string)
+ Include CustomerMixin

## CustomerMixin (object)
+ address (object)
+ customer_id (string)
```

Do you think employing these techniques would work for you as a workaround?

**Comment by lippea** [comment]
I ended up not using a solution from our developers, not the customized data structure.
Didn't manage to make it working.

**Comment by honzajavorek** [comment]
@lippea I'm sorry, I'm not sure I understood your comment. You didn't manage to get working inheritance or mixins? If that's the case, I can help with concrete examples using your data structures.
