### ISSUE TITLE
Undocumented parameters raise an exception

### ISSUE THREAD

**Issue by demianh** [apiaryio/dredd#469]
NPM updated my dredd to the latest release v1.1.0-pre.0, and now my tests are failing.

I think it has to do with parameters that aren't documented. See ?sort in "Document List", it is in the URL, but not listed in the documentation. 
In earlier versions of dredd, they just were omitted. Now i get an Exception. Not sure if this new behaviour is intended, but the old behaviour was definitely more convenient :)

I'll probably go and document all the undocumented parameters in each section anyway (currently they are documented as plain text in a common section) but i wanted to report this regression.

```apib
FORMAT: 1A

# My API

# Group Document

## Document List [/document{?sort}]

### Create Document [POST]
Create a document

+ Request
    [Document][]

+ Response 201

        18010

## Document [/document/{id}]
Get a document

+ Parameters
    + id (required, number, `1804`) ... Document ID.

+ Model (application/json)

    + Body

            {
                "title": "factsheet.pdf",
            }

```

I am calling dredd like this:

`/vagrant/node_modules/dredd/bin/dredd api/documentation/webling2.md http://demo.webling.dev/api/1`

Output:

```
warn:  Compilation warning in file 'api/documentation/webling2.md': 
Ambiguous URI parameter in template: /document{?sort} 
Parameter not defined in blueprint:'sort' on Document > Document List > Create Document 
info: Beginning Dredd testing...

/vagrant/node_modules/dredd/lib/transaction-runner.js:339
' + [this.parsedUrl['path'].replace(/^\/|\/$/g, ""), request['uri'].replace(/^
                                                                    ^
TypeError: Cannot call method 'replace' of null
  at TransactionRunner.configureTransaction (/vagrant/node_modules/dredd/lib/transaction-runner.js:339:88)
  at TransactionRunner.configureTransaction (/vagrant/node_modules/dredd/lib/transaction-runner.js:3:57)
  at /vagrant/node_modules/dredd/node_modules/async/lib/async.js:246:17
  at iterate (/vagrant/node_modules/dredd/node_modules/async/lib/async.js:146:13)
  at async.eachSeries (/vagrant/node_modules/dredd/node_modules/async/lib/async.js:162:9)
  at _asyncMap (/vagrant/node_modules/dredd/node_modules/async/lib/async.js:245:13)
  at Object.mapSeries (/vagrant/node_modules/dredd/node_modules/async/lib/async.js:228:23)
  at TransactionRunner.run (/vagrant/node_modules/dredd/lib/transaction-runner.js:56:11)
  at Dredd.startRunner (/vagrant/node_modules/dredd/lib/dredd.js:274:24)
  at /vagrant/node_modules/dredd/lib/dredd.js:115:28
  at /vagrant/node_modules/dredd/lib/dredd.js:266:18
  at EventEmitter.<anonymous> (/vagrant/node_modules/dredd/lib/reporters/cli-reporter.js:24:14)
  at EventEmitter.emit (events.js:117:20)
  at Dredd.emitStart (/vagrant/node_modules/dredd/lib/dredd.js:258:39)
  at /vagrant/node_modules/dredd/lib/dredd.js:111:26
  at /vagrant/node_modules/dredd/lib/dredd.js:249:16
  at done (/vagrant/node_modules/dredd/node_modules/async/lib/async.js:132:19)
  at /vagrant/node_modules/dredd/node_modules/async/lib/async.js:32:16
  at /vagrant/node_modules/dredd/lib/dredd.js:241:18
  at /vagrant/node_modules/dredd/node_modules/dredd-transactions/lib/dredd-transactions.js:31:14
  at /vagrant/node_modules/dredd/node_modules/dredd-transactions/lib/parse.js:17:12
```

**Comment by honzajavorek** [comment]
@demianh Thanks for trying out `v1.1.0-pre.0` and reporting this! That's very valuable feedback for us. It's definitely a bug, since even if we would like the behavior to change (and that's not the case actually), you should get normal error or warning, but not a stack trace.

**Comment by smizell** [comment]
@demianh I was able to figure this. Your input was great in helping me reproduce it. Thanks!

This issue requires two things to reproduce it.

First, use an ambiguous URI parameter. This means there is a parameter included in the URI template, but it is not defined in the blueprint. This example has one of these parameters.

```apib
FORMAT: 1A

# My API

# Item [/item{?foo}]
A parameter for `foo` should be defined here, however it's not.

## GET
+ Response 200
```

**Note**: if a directory is **not** included on the Dredd call, it results in a GET request to `null`.

```sh
$ dredd ./apiary.apib http://localhost:3000
warn:  Compilation warning in file './apiary.apib':
Ambiguous URI parameter in template: /item{?foo}
Parameter not defined in blueprint:'foo' on  > Item > GET
info: Beginning Dredd testing...
pass: GET null duration: 43ms
complete: 1 passing, 0 failing, 0 errors, 0 skipped, 1 total
complete: Tests took 48ms
```

Second, to get the error you are getting, you add a subdirectory to the Dredd call. Notice above I used `http://localhost:3000`. If I call with a subdirectory, I get this out:

```sh
$ dredd ./apiary.apib http://localhost:3000/foo
warn:  Compilation warning in file './apiary.apib':
Ambiguous URI parameter in template: /item{?foo}
Parameter not defined in blueprint:'foo' on  > Item > GET
info: Beginning Dredd testing...
/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/transaction-runner.js:339
      fullPath = '/' + [this.parsedUrl['path'].replace(/^\/|\/$/g, ""), request['uri'].replace(/^\/|\/$/g, "")].join("/");
                                                                                      ^

TypeError: Cannot read property 'replace' of null
  at TransactionRunner.configureTransaction (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/transaction-runner.js:339:87)
  at TransactionRunner.configureTransaction (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/transaction-runner.js:3:57)
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/async/lib/async.js:246:17
  at iterate (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/async/lib/async.js:146:13)
  at async.eachSeries (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/async/lib/async.js:162:9)
  at _asyncMap (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/async/lib/async.js:245:13)
  at Object.mapSeries (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/async/lib/async.js:228:23)
  at TransactionRunner.run (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/transaction-runner.js:56:11)
  at Dredd.startRunner (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/dredd.js:274:24)
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/dredd.js:115:28
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/dredd.js:266:18
  at EventEmitter.<anonymous> (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/reporters/cli-reporter.js:24:14)
  at emitTwo (events.js:92:20)
  at EventEmitter.emit (events.js:172:7)
  at Dredd.emitStart (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/dredd.js:258:39)
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/dredd.js:111:26
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/dredd.js:249:16
  at done (/Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/async/lib/async.js:132:19)
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/async/lib/async.js:32:16
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/lib/dredd.js:241:18
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/dredd-transactions/lib/dredd-transactions.js:31:14
  at /Users/smizell/.nvm/versions/node/v5.0.0/lib/node_modules/dredd/node_modules/dredd-transactions/lib/parse.js:17:12
```

@demianh would you be able to confirm this is the situation for you? When you remove the subdirectory from your dredd command, does the exception go away?

And thanks a ton for reporting this. I'm sorry your build was broken!  We definitely want to prevent that from happening.

**Comment by demianh** [comment]
@smizell yes, i can confirm that removing the subfolder from the url makes the error go away (tested with v1.1.0-pre.1 this time)

**Comment by honzajavorek** [comment]
The problem seems to be that now `dredd-transactions` do pass such transaction to Dredd although in the past they did not. Working on a fix.
