### ISSUE TITLE
Unable to run on Ubuntu 14.04

### ISSUE THREAD

**Issue by frexin** [apiaryio/dredd#480]
I just installed dredd on my virtualbox with Ubuntu 14.04 i386.
But i'm always getting this strange error:

root@frexinvbox:/tmp# dredd -v
/usr/local/lib/node_modules/dredd/node_modules/coffee-script/lib/coffee-script/register.js:45
      Module._extensions[extension](this, filename);
                                   ^
Error: /usr/local/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/protagonist/build/Release/protagonist.node: file too short
  at Module.load (/usr/local/lib/node_modules/dredd/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/dredd-transactions/lib/parse.js:4:15)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/dredd/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/dredd-transactions/lib/dredd-transactions.js:4:9)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/dredd/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/dredd/lib/dredd.js:25:21)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/dredd/lib/dredd-command.js:18:9)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/dredd/bin/dredd:6:20)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

**Comment by pksunkara** [comment]
Can you try running it using `sudo`?

**Comment by klokane** [comment]
For start, pls paste here result of:
```
$ ls -la /usr/local/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/protagonist/build/Release/protagonist.node
```

and 
```
file /usr/local/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/protagonist/build/Release/protagonist.node
```

**Comment by pksunkara** [comment]
He probably doesn't have access to the folder where `protagonist.node` is lying which is why I asked him to try sudo.

**Comment by honzajavorek** [comment]
This should be now solved by [installing Dredd without compilation](http://dredd.readthedocs.io/en/latest/installation/#compiled-vs-pure-javascript).
