### ISSUE TITLE
Exception in async beforeAll hook will crash reporters.

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#576]
`hooks.js`:
```js
var hooks = require('hooks');

hooks.beforeAll(function(callback){
  throw("Hooks exception");
  callback();
});
```

command:
```
$ dredd apiary.apib http://localhost:3000 --hookfiles=hooks.js -r apiary
```

result:
```
complete: Tests took 450ms
/Users/netmilk/.nvm/versions/node/v6.2.0/lib/node_modules/dredd/lib/reporters/apiary-reporter.js:186
          return callback();
                 ^

TypeError: callback is not a function
  at /Users/netmilk/.nvm/versions/node/v6.2.0/lib/node_modules/dredd/lib/reporters/apiary-reporter.js:186:18
  at IncomingMessage.<anonymous> (/Users/netmilk/.nvm/versions/node/v6.2.0/lib/node_modules/dredd/lib/reporters/apiary-reporter.js:271:18)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:926:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by honzajavorek** [comment]
I think this might get fixed by #648, but without test, we can't be sure.

**Comment by honzajavorek** [comment]
Related to https://github.com/apiaryio/dredd/issues/692, I'd say.
