### ISSUE TITLE
fatal error: 'uv.h' file not found #include "uv.h"

### ISSUE THREAD

**Issue by TangMonk** [apiaryio/dredd#61]
Try to `npm install -g dredd`, but alert me:

```
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.21","npm":"1.3.11"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.21","npm":"1.3.11"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.21","npm":"1.3.11"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.21","npm":"1.3.11"})
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/ParserCore.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Serialize.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeJSON.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeYAML.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/snowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/posix/RegexMatch.o
  LIBTOOL-STATIC Release/snowcrash.a
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/autolink.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/buffer.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/html.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/html_smartypants.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/markdown.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/stack.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/src_map.o
  LIBTOOL-STATIC Release/sundown.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from ../src/annotation.cc:1:
In file included from ../src/protagonist.h:1:
/Users/tangmonk/.node-gyp/0.10.21/src/node.h:61:10: fatal error: 'uv.h' file not found
#include "uv.h"
         ^
1 error generated.
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/dredd/node_modules/protagonist
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by TNikolai** [comment]
TangMonk could you write which steps concrete you made, to update node?
