### ISSUE TITLE
Flaky test: "when using language hook handler and spawning the server and handler is killed during execution"

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#756]
Looks like there's another annoying flaky little fellow in the Windows test suite:

```
  1) CLI when called with arguments when using language hook handler and spawning the server and handler is killed during execution "before all" hook:
     Error: done() called multiple times
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:225:11)
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:222:9)
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:92:7)
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:91:5)
      at Object.<anonymous> (test\integration\cli\cli-test.coffee:16:3)
      at Object.<anonymous> (test\integration\cli\cli-test.coffee:923:4)
      at Object.loadFile (node_modules\coffee-script\lib\coffee-script\register.js:16:19)
      at Module.load (node_modules\coffee-script\lib\coffee-script\register.js:45:36)
      at require (internal/module.js:20:19)
      at Array.forEach (native)
      at run (bootstrap_node.js:394:7)
      at startup (bootstrap_node.js:149:9)
      at bootstrap_node.js:509:3
  2) CLI when called with arguments when using language hook handler and spawning the server and handler is killed during execution "before all" hook:
     Error: done() called multiple times
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:225:11)
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:222:9)
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:92:7)
      at Suite.<anonymous> (test\integration\cli\cli-test.coffee:91:5)
      at Object.<anonymous> (test\integration\cli\cli-test.coffee:16:3)
      at Object.<anonymous> (test\integration\cli\cli-test.coffee:923:4)
      at Object.loadFile (node_modules\coffee-script\lib\coffee-script\register.js:16:19)
      at Module.load (node_modules\coffee-script\lib\coffee-script\register.js:45:36)
      at require (internal/module.js:20:19)
      at Array.forEach (native)
      at run (bootstrap_node.js:394:7)
      at startup (bootstrap_node.js:149:9)
      at bootstrap_node.js:509:3
```

**Comment by honzajavorek** [comment]
It can also look like this:

```
  1) CLI when called with arguments when using language hook handler and spawning the server and handler is killed during execution should return with status 1:
      AssertionError: expected 0 to equal 1
      + expected - actual
      -0
      +1
      
      at Context.<anonymous> (test\integration\cli\cli-test.coffee:226:18)
  
  2) CLI when called with arguments when using language hook handler and spawning the server and handler is killed during execution should return message announcing the fact:
     AssertionError: expected '' to include 'exited'
      at Context.<anonymous> (test\integration\cli\cli-test.coffee:231:20)
```

**Comment by honzajavorek** [comment]
Most likely fixed, let's close this and reopen if we see it again.
