### ISSUE TITLE
Dredd Cannot read property 'element' of undefined issue

### ISSUE THREAD

**Issue by tislib** [apiaryio/dredd#817]
#### Describe your problem
Hi, 
dredd gives following error: 

```
TypeError: Cannot read property 'element' of undefined
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:14:23)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:101:23)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at Array.map (native)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:104:22)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:97:19)
    at constructor.dataStructureSerialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:57:18)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:35:70)
    at Array.map (native)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:104:22)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at Array.map (native)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:104:22)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at Array.map (native)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:104:22)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at Array.map (native)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:104:22)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at Array.map (native)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:104:22)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at Array.map (native)
    at constructor.serialiseContent (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:104:22)
    at constructor.serialise (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\minim\lib\serialisers\json-0.6.js:37:33)
    at module.exports (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\dredd-transactions\lib\api-elements-to-json.js:9:45)
    at compile (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\dredd-transactions\lib\compile.js:22:17)
    at C:\sbm\bmmain\sbm\cxprocessportal\node_modules\dredd-transactions\lib\dredd-transactions.js:30:16
    at C:\sbm\bmmain\sbm\cxprocessportal\node_modules\dredd-transactions\lib\parse.js:47:12
    at C:\sbm\bmmain\sbm\cxprocessportal\node_modules\fury\lib\fury.js:169:13
    at complete (C:\sbm\bmmain\sbm\cxprocessportal\node_modules\fury-adapter-swagger\lib\parser.js:258:20)
    at C:\sbm\bmmain\sbm\cxprocessportal\node_modules\fury-adapter-swagger\lib\parser.js:280:17
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

I have checked in multiple system, it gives same error. 

I try to use swagger file, in that case this error occures, if blueprint file used, everyting is ok. 
I realized that in yaml file dredd cannot parse type: integer, if type: string is written, everyting is ok
```
Error:
    type: object
    properties:
      code:
        **type: integer**
      message:
        type: string
      fields:
        type: string

```

I am using latest version. I checked it in several operation system ( mac, linux, windows ) it is not working in any of it.
Thanks

**Comment by honzajavorek** [comment]
This looks like something we might have caused with @kylef by https://github.com/apiaryio/dredd-transactions/pull/80 yesterday or by one of the other recent Pull Requests on Dredd Transactions. Would you please try out whether one of the previous versions work correctly?

We'll try to look into it meanwhile.

**Comment by tislib** [comment]
Yes, I have checked it with dredd-transactions previous version. It is working properly. 
Thanks

**Comment by kylef** [comment]
Hi @tislib, would you be able to provide me with the full Swagger document that is causing this problem so I can reproduce and solve it easier. Feel free to email it to me: `kyle.fuller@oracle.com`.

Thanks!

**Comment by josh91hickman** [comment]
@ tislib & @honzajavorek ran into this issue today, how did you go about fixing?

**Comment by honzajavorek** [comment]
We're still about to find the root cause. Workaround is to downgrade Dredd Transactions meanwhile.

**Comment by honzajavorek** [comment]
Not correct, we already have https://github.com/apiaryio/dredd-transactions/pull/81 to fix this.
