### ISSUE TITLE
Configuration option path is required in dredd.yml

### ISSUE THREAD

**Issue by spawnia** [apiaryio/dredd#959]
#### Describe your problem
I configured dredd by putting my configuration options in `dredd.yml`. I like to keep my configuration simple, so i left out the default values. When i do not explicitely set `path: []`, i run into the error shown in the output below. It would be nice if dredd could handle the default gracefully.

#### What command line options do you use?
I run the following in my project root inside of a docker container (node:9.4.0-alpine)
```
$ node_modules/.bin/dredd
```

#### What is in your `dredd.yml`?

```yaml
endpoint: web
hookfiles: "tests/dredd/hooks/*.php"
language: php
blueprint: api-description.apib

hooks-worker-handler-host: php

path: []
```

#### What's your `dredd --version` output?

```
dredd v5.0.0 (Linux 3.10.0-693.11.6.el7.x86_64; x64)
```

#### Does `dredd --level=debug` uncover something?
````
info: Configuration './dredd.yml' found, ignoring other arguments.
debug: Dredd version: 5.0.0
debug: Node.js version: v9.4.0
debug: Node.js environment: http_parser=2.7.0, node=9.4.0, v8=6.2.414.46-node.17, uv=1.18.0, zlib=1.2.11, ares=1.13.0, modules=59, nghttp2=1.29.0, openssl=1.0.2n, icu=60.1, unicode=10.0, cldr=32.0, tz=2017c
debug: System version: Linux 3.10.0-693.11.6.el7.x86_64 x64
debug: npm version: 5.6.0
debug: Configuration: {"server":"web","options":{"hookfiles":"tests/dredd/hooks/*.php","language":"php","hooks-worker-handler-host":"php","level":"debug","_":["api-description.apib"],"p":[null,"api-description.apib","api-description.apib"],"path":[null,"api-description.apib","api-description.apib"]},"custom":{"cwd":"/home/node/app","argv":[]}}
verbose: Using 'base' reporter.
verbose: Configuring reporters: []
verbose: Using 'cli' reporter.
verbose: No backend server process specified, starting testing at once
verbose: Running Dredd instance.
verbose: Expanding glob patterns.
error: glob pattern string required TypeError: glob pattern string required
    at new Minimatch (/home/node/app/node_modules/minimatch/minimatch.js:116:11)
    at setopts (/home/node/app/node_modules/glob/common.js:113:20)
    at new Glob (/home/node/app/node_modules/glob/glob.js:131:3)
    at glob (/home/node/app/node_modules/glob/glob.js:75:10)
    at async.each (/home/node/app/node_modules/dredd/lib/dredd.js:211:7)
    at /home/node/app/node_modules/async/dist/async.js:3047:16
    at eachOfArrayLike (/home/node/app/node_modules/async/dist/async.js:1039:9)
    at eachOf (/home/node/app/node_modules/async/dist/async.js:1087:5)
    at Object.eachLimit (/home/node/app/node_modules/async/dist/async.js:3109:3)
    at Dredd.expandGlobs (/home/node/app/node_modules/dredd/lib/dredd.js:205:11)
    at Dredd.run (/home/node/app/node_modules/dredd/lib/dredd.js:165:10)
    at DreddCommand.runDredd (/home/node/app/node_modules/dredd/lib/dredd-command.js:388:19)
    at DreddCommand.runServerAndThenDredd (/home/node/app/node_modules/dredd/lib/dredd-command.js:235:12)
    at DreddCommand.run (/home/node/app/node_modules/dredd/lib/dredd-command.js:328:12)
    at Object.<anonymous> (/home/node/app/node_modules/dredd/bin/dredd:58:10)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

verbose: No backend server process to terminate.
verbose: Exiting Dredd process with status '2'.
debug: Using native process.exit() method to terminate the Dredd process.
verbose: No backend server process to terminate.
````

**Comment by honzajavorek** [comment]
@spawnia Thanks! This is something I've met previously as well. But it looks like I forgot to file an issue. This is an important bug we need to resolve once we're revamping the config.

**Comment by honzajavorek** [comment]
@spawnia we did rework the configuration recently. Could you please verify this has been fixed? Thanks! 🙏

**Comment by spawnia** [comment]
@honzajavorek thanks for the feedback. I am no longer using dredd - it is all GraphQL for us now - so i don't have a project to validate this is working.
